apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-a
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: type-a
  template:
    metadata:
      labels:
        app: type-a
    spec:
      containers:
      - name: a-giftwrapped-container
        image: gcr.io/$PROJECT_ID/regis:$COMMIT_SHA
        ports:
        - containerPort: 80